# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
jobs:
  installAndTest:
      executor:
        name: node/default
        tag: '16.12-browsers'
      steps:
        - checkout
        - run: DISPLAY=:0
        - run: sudo apt-get update && sudo apt-get install -y libxshmfence-dev libnss3-tools libatk1.0-0 libatk-bridge2.0-0 libdrm2 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libasound2
        - run: npm install electron
        - node/install-packages:
            cache-path: ~/project/node_modules
            override-ci-command: npm install
        - run: sudo npm install -g npm@latest
        - run: cd app
        - run: sudo npm install -g npm@latest
        - run: npm run test
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - installAndTest